kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-forklift-inventory-endpoint
stringData:
  server-url: https://forklift-inventory-openshift-mtv.apps.forklift-test-1.zbvs.p1.openshiftapps.com
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sa
  annotations:
    kubernetes.io/service-account.name: "{{ .Release.Name }}"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-admin-restaction
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: {{ .Release.Name }}
spec:
  api:
  - name: getToken
    path: /api/v1/namespaces/{{ .Release.Namespace }}/secrets/{{ .Release.Name }}-sa
    verb: GET
    filter: .getToken.data.token | @base64d
    errorKey: getTokenError
  - name: getUidProvider
    dependsOn:
      name: getToken
    path: /providers
    verb: GET
    headers:
    - "${ \"Authorization: Bearer \" + .getToken }"
    endpointRef:
      name: {{ .Release.Name }}-forklift-inventory-endpoint
      namespace: {{ .Release.Namespace }}
    filter: >
      .getUidProvider.vsphere[] | select(.name=="{{ .Release.Name }}") | .id
    errorKey: getUidProviderError
  - name: vms
    dependsOn:
      name: getUidProvider
    endpointRef:
      name: {{ .Release.Name }}-forklift-inventory-endpoint
      namespace: {{ .Release.Namespace }}
    headers:
    - "${ \"Authorization: Bearer \" + .getToken }"
    path: ${ "/providers/vsphere/" + .getUidProvider + "/vms" }
    filter: >
      [ .vms.[] | {id: .id, name: .name} ]
    verb: GET
    errorKey: vmsError
  filter: .vms