apiVersion: forklift.konveyor.io/v1beta1
kind: Plan
metadata:
  annotations:
    populatorLabels: 'True'
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  pvcNameTemplateUseGenerateName: true
  warm: false
  migrateSharedDisks: true
  targetNamespace: {{ .Release.Namespace }}
  useCompatibilityMode: true
  skipGuestConversion: false
  provider:
    destination:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: host
      namespace: openshift-mtv
    source:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
  preserveStaticIPs: false
  type: cold
  vms:
{{ toYaml .Values.plan.vms | nindent 4 }}
  map:
    network:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: NetworkMap
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
    storage:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: StorageMap
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
  runPreflightInspection: true
  targetPowerState: auto