apiVersion: forklift.konveyor.io/v1beta1
kind: NetworkMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  map:
    - destination:
        type: pod
      source:
        id: HaNetwork-VM Network
  provider:
    destination:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: host
      namespace: {{ .Release.Namespace }}
    source:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}