apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  map:
    - destination:
        storageClass: gp3-csi
      source:
        id: 693ae9d4-571997ac-8043-d05099dadcab
        name: datastore_sata
  provider:
    destination:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: host
      namespace: {{ .Release.Namespace }}
    source:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}